# 将feign包下产生的日志的级别设置为debug
logging:
  level:
    com.atguigu.spzx.cloud.order.feign: debug

# openfeign日志级别配置
spring:
  cloud:
    openfeign:
      client:
        config:
          spzx-cloud-user:   # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
            loggerLevel: full
            read-timeout: 2000            # 读取数据的超时时间设置为2s
            connect-timeout: 2000        # 简历连接的超时时间设置为2s
            retryer: com.atguigu.spzx.cloud.feign.config.FeignClientRetryer		# 配置自定义重试器