# 配置服务端口号
server:
  port: 10100

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.186.102:3306/spzx_cloud_user?characterEncoding=UTF8
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.186.102:8848
        namespace: dev
        cluster-name: HB
        enabled: true
      # 配置nacos的配置中心,一些重要的数据写在程序的配置文件是不安全的,我们可以把它写在nacos的配置中心中
      config:
        server-addr: 192.168.186.102:8848
        namespace: dev
    sentinel:
      transport:
        dashboard: 192.168.186.102:8858

  application:
    name: spzx-cloud-user
  #引入外部配置文件
  config:
    import:
      - nacos:spzx-cloud-user.yaml

# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.atguigu.spzx.cloud.user.entity
  mapper-locations: classpath:/mapper/*.xml


management:
  endpoints:
    web:
      exposure:
        include: "*"    # 开启所有需要监控的指标端点
  endpoint:
    health:
      show-details: always