server:
  port: 80

spring:
  application:
    name: spzx-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.186.102:8848
        namespace: dev
    gateway:
      routes:
        - id: spzx-cloud-user				# 路由id，可以自定义，只要唯一即可
          uri: lb://spzx-cloud-user		    # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/*/user/**			    # 这个是按照路径匹配，只要以/user/开头就符合要求
          filters:
            - AddRequestHeader=X-Request-foo,userBar
        - id: spzx-cloud-order
          uri: lb://spzx-cloud-order
          predicates:
            - Path=/*/order/**
          #网关过滤器,当通过网关访问order的时候,会为该请求添加一个请求头该请求头
          filters:
            - AddRequestHeader=X-Request-foo,orderBar
      #当默认过滤器和路由过滤器同时出现时，路由过滤器会把默认过滤器覆盖
      default-filters:
        - AddRequestHeader=X-Request-foo,orderBar


management:
  endpoints:
    web:
      exposure:
        include: "*"    # 开启所有需要监控的指标端点
  endpoint:
    health:
      show-details: always